### ISSUE TITLE
Any way to include language names isntead of just language codes?

### ISSUE THREAD

**Issue by thiagomajesk** [SebastianSzturo/countries#50]
Something like:

```yaml
languages_official:
  en: english
languages_spoken:
  en: english
```

```elixir
%Country {
  languages_official: %{"en" => "english"}
  languages_spoken: %{"en" => "english"}
}
```
